variables:
  CI_REGISTRY: registry.gitlab.com
  PIPELINE_RUNNER: registry.gitlab.com/darklab2/darklab_pipeliner/darklab-pipeliner:kubectl-v1.0.3

stages:
  - deploy1

deploying_container:
  image: ${PIPELINE_RUNNER}
  stage: deploy1
  variables:
    DOCKER_HOST: tcp://dind-service:2375
  script:
    - echo 123
    - mkdir ~/.kube
    - echo "${kubectl_config}" > ~/.kube/config
    - kubectl get pods --all-namespaces
    - python3 install.py